### ISSUE TITLE
Failing to mount volume in template pipelines.

### ISSUE THREAD

**Issue by MohamadTahir** [spritsail/drone-docker-publish#1]
Hello, I am trying to use your image in drone pipelines, here is my pipeline and below is the error message I am getting, 

I am running the server as a pod on our K8S Cluster, and the runner is running on a docker container on vm.

```
kind: pipeline
type: docker
name: default
trigger:
  ref:
    - refs/heads/dev
    - refs/heads/main
    - refs/tags/v*
  event:
    - push
    - tag

steps:
  - name: build and push
    image: spritsail/docker-publish
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password ]
    from: local-built-image
    repo: spritsail/docker-publish
    registry: registry.foobar.io
    tags:
      - latest
```

```
{"commit":"d8a9b95f22caa1fb73368754faca348e32a36c67","error":"yaml: unmarshal errors:\n  line 16: cannot unmarshal !!str `/var/ru...` into yaml.VolumeMount","event":"push","level":"warning","msg":"trigger: cannot parse yaml","ref":"refs/heads/dev","repo":"MohamadTahir/drone-test","time":"2023-04-28T23:57:12Z"}
```
